### ISSUE TITLE
South integration

### ISSUE THREAD

**Issue by bluekite2000** [callmephilip/django-heroku-bootstrap#1]
When I do fab run I get
 File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/django/db/models/loading.py", line 149, in get_app
    raise ImproperlyConfigured("App with label %s is missing a models.py module." % app_label)
django.core.exceptions.ImproperlyConfigured: App with label examples is missing a models.py module.

I see you have committed code on south integration. Would love it if you update the readme so I can try it out. Thanks

**Comment by callmephilip** [comment]
Will do. The repository is in a somewhat in-between state right now. I'll fix this shortly

**Comment by bluekite2000** [comment]
When I do fab run I get error.
Not sure if its related to migration or not

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/django/core/management/**init**.py", line 459, in execute_manager
    utility.execute()
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/south/management/commands/schemamigration.py", line 76, in handle
    migrations = Migrations(app, force_creation=True, verbose_creation=int(verbosity) > 0)
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/south/migration/base.py", line 61, in **call**
    self.instances[app_label] = super(MigrationsMetaclass, self).**call**(app_label_to_app_module(app_label), **kwds)
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/south/migration/utils.py", line 41, in app_label_to_app_module
    app = models.get_app(app_label)
  File "/Users/trang/.virtualenvs/djangoheroku/lib/python2.7/site-packages/django/db/models/loading.py", line 149, in get_app
    raise ImproperlyConfigured("App with label %s is missing a models.py module." % app_label)
django.core.exceptions.ImproperlyConfigured: App with label examples is missing a models.py module.

Fatal error: local() encountered an error (return code 1) while executing 'python manage.py schemamigration apps.examples --initial --settings=settings.dev'

Aborting.

**Comment by callmephilip** [comment]
I believe it is. The example app in the apps module does not have a models module. South is not happy about that. As I said, I will update the bootstrap to bring it to a coherent state + fresh docs. Thanks for help in tracking that down

**Comment by bluekite2000** [comment]
I m trying to run on my local machine. When I do fab run I get an error
raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
21:00:52 web.1  | ImportError: Could not import settings 'settings.dev' (Is it on sys.path?): No module named settings.dev

I believe it has something to do with 

web: gunicorn_django -b 0.0.0.0:$PORT -w 9 -k gevent --max-requests 250 --preload settings.dev

any idea?

**Comment by callmephilip** [comment]
My guess is that current directory ('.') is not on your python path. Try the following: 
1. in the python console:
   import sys
   print sys.path
2. check to see if current directory ('.') is within the list. If not, you might want to add it through an environmental variable in your system (export PYTHONPATH=${PYTHONPATH}:.)

**Comment by callmephilip** [comment]
I will add automatic path appending to the fab script so you won't have to worry about it in the future

**Comment by callmephilip** [comment]
Hey Dat. I've made some changes to the bootstrap that should resolve the problems you've been having. Please let me know if it works. South migrations should work as well.

**Comment by bluekite2000** [comment]
I keep getting table does not exist error.
plus can you separate staging and production sites on heroku?
i keep getting
 !    Multiple apps in folder and no app specified.
when I tried to do it

**Comment by callmephilip** [comment]
could you provide trace logs, por favor?
